name: Preview Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Run Npm Scripts
        run: |
          node -v
          npm install pnpm -g
          pnpm -v
          pnpm i
          pnpm scripts run build
